spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USER:ulysses}
    password: ${RABBIT_PASSWORD:senha123}
  application:
      name: notification-ms

resend:
  api-key: ${RESEND_TOKEN:""}